name: Load testing workflow
on: [push, workflow_dispatch]

jobs:
  test:
    name: Run load test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run k6 local test
        uses: k6io/action@v0.1
        with:
          filename: introduction-demo.js
          flags: --out influxdb=http://1c98-84-63-219-214.ngrok.ioo
      

